"""initial

Revision ID: 78df2d15b074
Revises: 
Create Date: 2026-07-08 18:05:11.991497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78df2d15b074'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('drafted', sa.Integer(), nullable=False),
    sa.Column('failed_records', sa.Integer(), nullable=False),
    sa.Column('total_billed', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('agent', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_run_id'), 'audit_events', ['run_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('payer', sa.String(), nullable=False),
    sa.Column('carc_code', sa.String(), nullable=False),
    sa.Column('rarc_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('billed_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('denial_date', sa.Date(), nullable=False),
    sa.Column('appeal_deadline', sa.Date(), nullable=True),
    sa.Column('denial_reason_text', sa.Text(), nullable=False),
    sa.Column('carc_text', sa.Text(), nullable=True),
    sa.Column('letter', sa.Text(), nullable=True),
    sa.Column('letter_original', sa.Text(), nullable=True),
    sa.Column('refined', sa.Text(), nullable=True),
    sa.Column('rule', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_run_id'), 'claims', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_run_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_audit_events_run_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('runs')
    # ### end Alembic commands ###
